PXB-2477 (xbcloud should retry on error and utilize incremental backoff)
https://jira.percona.com/browse/PXB-2477

Problem
Currently we only support retries on s3 api for upload/put action.
The current implementation retries 3 times without any delay in between
attemps. This is goes against network transmission best practices.

Solution
* Implemented retry callback for swift (upload/download) and
 S3 (download) - upload was already implemented.

* Implement truncated exponential backoff to avoid network congestion.
 This alows users to choose how many times they will want a chunk to be
 retransmitted before erroring out. Also, users will have the ability to
 choose a maximum delay in between retries, in which the exponential
 time delay will stop increasing while still retrying.

* Added an option to extend the fixed list of curl/http errors that will
be considered as retriable. This can be used with --verbose flag to display
which error curl/http has returned and which parameter value has to be added
in order to allow that extra error(s).

* Fixed some swift error messages that were missing \n.

* Fixed Http_client::make_async_request to report generic action, as it
had "upload object" action hardcoded.

* Merged callbacks to a single generic Http_client function

* added call to a client specific method that will allow API client
specific error retry logic. All new cloud client will implement it.

* Increased max retries default from 3 to 10 to make defaults more reliable.

--------------------------------------------------------------------------

Impĺemented PXB-2580 - xbcloud: retry chunk-upload on SSL connect error

https://jira.percona.com/browse/PXB-2580

(cherry picked from commit 72d17794cc71057f4cb34d0b6f913e0564f225a0)

--------------------------------------------------------------------------

PXB-2625 - Error in the HTTP2 framing layer / Large backup fails on Debian Buster

https://jira.percona.com/browse/PXB-2625

Problem:
In some version of curl after 7.52.1 (default for Debian 9/Stretch) and
version 7.64.0 (default for Debian 10/Buster) a regression was
introduced that caused curl fail to identify a TLS HTTP2 connection was
closed and it tried to re-use the closed connection causing xbcloud
fail to download / upload chunks with 'Error in the HTTP2 framing layer'
message / Curl error code 16 - CURLE_HTTP2.

Fix:
Curl has fixed it at
https://github.com/curl/curl/commit/3f5da4e59a556fc68272a9857a38dd75234d0c04
and delivered it on 7.65.0. For users that cannot update the curl
version and to provide a better user experience by making the backup to
complete we are adding error CURLE_HTTP2 retriable by default.

Thanks to Johan Andersson for reporting and helping troubleshooting.

--------------------------------------------------------------------------

Fixed PXB-2648 - error: 'CURLE_HTTP2' is not a member of 'CURLcode'

https://jira.percona.com/browse/PXB-2648

Problem:
Curl version prior to 7.38.0 doesn't have CURLE_HTTP2, it has
CURLE_OBSOLETE16.

Fix:
Use CURLE_OBSOLETE16. On newer versions of libcurl it has an alias
that translates CURLE_OBSOLETE16 to CURLE_HTTP2.

(cherry picked from commit 8c540c168165f4017bf5f314e4d95383b8bee028)