Fixed PXB-2648 - error: 'CURLE_HTTP2' is not a member of 'CURLcode'
https://jira.percona.com/browse/PXB-2648

Problem:
Curl version prior to 7.38.0 doesn't have CURLE_HTTP2, it has
CURLE_OBSOLETE16.

Fix:
Use CURLE_OBSOLETE16. On newer versions of libcurl it has an alias
that translates CURLE_OBSOLETE16 to CURLE_HTTP2.

(cherry picked from commit 8c540c168165f4017bf5f314e4d95383b8bee028)